(define (domain typed-move)
  (:requirements :strips :typing)
  (:types room hall)
  (:predicates
    (at-room ?x - room)
    (at-hall ?x - hall)
    (connected-rr ?a - room ?b - room)
    (connected-rh ?a - room ?b - hall)
    (connected-hr ?a - hall ?b - room)
    (connected-hh ?a - hall ?b - hall)
    (safe-room ?x - room)
    (safe-hall ?x - hall)
  )
  (:action move-rh
    :parameters (?a - room ?b - hall)
    :precondition (and (at-room ?a) (connected-rh ?a ?b) (safe-hall ?b))
    :effect (and (not (at-room ?a)) (at-hall ?b))
  )
  (:action move-hr
    :parameters (?a - hall ?b - room)
    :precondition (and (at-hall ?a) (connected-hr ?a ?b) (safe-room ?b))
    :effect (and (not (at-hall ?a)) (at-room ?b))
  )
)
